# Generated by Django 5.0.7 on 2026-01-07 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventhall",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Price based on selected pricing type",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="eventhall",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("PER_HOUR", "Per Hour"),
                    ("PER_DAY", "Per Day"),
                    ("PER_EVENT", "Per Event"),
                ],
                default="PER_HOUR",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventhall",
            name="price_per_hour",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.CreateModel(
            name="EventHallImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="event_halls/gallery/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="events.eventhall",
                    ),
                ),
            ],
        ),
    ]
