# Generated by Django 5.0.7 on 2026-01-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_eventhall_price_eventhall_pricing_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventbooking",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="event_qr_codes/"),
        ),
    ]
