# Generated by Django 5.0.7 on 2026-01-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("BOOKING", "Booking"),
                    ("EVENT", "Event"),
                    ("GYM", "Gym"),
                    ("SUBSCRIPTION", "Subscription"),
                    ("OTHER", "Other"),
                ],
                default="BOOKING",
                max_length=20,
            ),
        ),
    ]
