# Generated by Django 5.0.7 on 2026-01-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentGateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("PAYSTACK", "Paystack"),
                            ("FLUTTERWAVE", "Flutterwave"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("public_key", models.CharField(max_length=255)),
                ("secret_key", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("PAYSTACK", "Paystack"),
                    ("FLUTTERWAVE", "Flutterwave"),
                    ("TRANSFER", "Bank Transfer"),
                ],
                max_length=20,
            ),
        ),
    ]
