# Generated by Django 5.0.7 on 2026-01-07 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_paymentgateway_alter_payment_payment_method"),
        ("booking", "0002_alter_booking_check_in_date_and_more"),
        ("events", "0002_eventhall_price_eventhall_pricing_type_and_more"),
        ("gym", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="event_booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="events.eventbooking",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="gym_membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="gym.gymmembership",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="booking.booking",
            ),
        ),
    ]
