# Generated by Django 5.0.7 on 2026-01-11 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_tenant'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='is_test_mode',
            field=models.BooleanField(default=True, help_text='Check to use Test Keys'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateways', to='tenants.tenant'),
        ),
    ]
