# Generated by Django 5.0.7 on 2026-01-13 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_host",
                    models.CharField(default="mail.techohr.com.ng", max_length=255),
                ),
                ("email_port", models.IntegerField(default=465)),
                (
                    "email_host_user",
                    models.CharField(default="ihotel@techohr.com.ng", max_length=255),
                ),
                ("email_host_password", models.CharField(blank=True, max_length=255)),
                ("email_use_tls", models.BooleanField(default=False)),
                ("email_use_ssl", models.BooleanField(default=True)),
                (
                    "default_from_email",
                    models.EmailField(default="ihotel@techohr.com.ng", max_length=254),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("SUCCESS", "Success"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("link", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TenantSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("theme-default", "Default Dark"),
                            ("theme-light", "Light Mode"),
                            ("theme-blue", "Blue Horizon"),
                            ("theme-luxury", "Gold Luxury"),
                            ("theme-forest", "Forest Green"),
                            ("theme-ocean", "Ocean Breeze"),
                            ("theme-sunset", "Sunset Vibes"),
                            ("theme-royal", "Royal Purple"),
                            ("theme-minimal", "Minimalist Mono"),
                            ("theme-rose", "Rose Garden"),
                            ("theme-coffee", "Coffee Break"),
                            ("theme-lavender", "Lavender Mist"),
                            ("theme-midnight", "Midnight Run"),
                            ("theme-neon", "Neon Cyberpunk"),
                            ("theme-retro", "Retro Wave"),
                            ("theme-cherry", "Cherry Blossom"),
                            ("theme-dracula", "Dracula Dark"),
                            ("theme-corporate", "Corporate Professional"),
                            ("theme-custom", "Custom Theme"),
                        ],
                        default="theme-default",
                        max_length=50,
                    ),
                ),
                (
                    "custom_primary_color",
                    models.CharField(
                        default="#13ec6d",
                        help_text="Hex code for primary color",
                        max_length=7,
                    ),
                ),
                (
                    "custom_background_color",
                    models.CharField(
                        default="#0f172a",
                        help_text="Hex code for background color",
                        max_length=7,
                    ),
                ),
                (
                    "custom_surface_color",
                    models.CharField(
                        default="#1e293b",
                        help_text="Hex code for surface/card color",
                        max_length=7,
                    ),
                ),
                ("hotel_name", models.CharField(default="My Hotel", max_length=255)),
                (
                    "hotel_logo",
                    models.ImageField(blank=True, null=True, upload_to="site/"),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "USD ($)"),
                            ("EUR", "EUR (€)"),
                            ("GBP", "GBP (£)"),
                            ("NGN", "NGN (₦)"),
                            ("JPY", "JPY (¥)"),
                            ("CAD", "CAD ($)"),
                            ("AUD", "AUD ($)"),
                            ("INR", "INR (₹)"),
                            ("ZAR", "ZAR (R)"),
                        ],
                        default="USD",
                        max_length=10,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(default="info@example.com", max_length=254),
                ),
                (
                    "contact_phone",
                    models.CharField(default="+1 234 567 8900", max_length=50),
                ),
                ("address", models.TextField(default="123 Luxury Ave, City")),
                (
                    "housekeeping_info",
                    models.TextField(
                        blank=True,
                        default="Standard housekeeping is available from 9:00 AM to 5:00 PM daily. Please request special services at least 2 hours in advance.",
                        help_text="Information about cleaning schedules and policies.",
                    ),
                ),
                ("facebook_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                (
                    "enable_events",
                    models.BooleanField(
                        default=False,
                        help_text="Enable Events Management module (Halls, Bookings)",
                    ),
                ),
                (
                    "enable_gym",
                    models.BooleanField(
                        default=False,
                        help_text="Enable Gym & Fitness module (Memberships, Access)",
                    ),
                ),
                (
                    "email_host",
                    models.CharField(
                        blank=True,
                        help_text="SMTP Server (e.g., smtp.gmail.com)",
                        max_length=255,
                    ),
                ),
                (
                    "email_port",
                    models.IntegerField(
                        default=587, help_text="SMTP Port (e.g., 587 or 465)"
                    ),
                ),
                (
                    "email_host_user",
                    models.CharField(
                        blank=True, help_text="Email Address", max_length=255
                    ),
                ),
                (
                    "email_host_password",
                    models.CharField(
                        blank=True, help_text="Email Password", max_length=255
                    ),
                ),
                (
                    "email_use_tls",
                    models.BooleanField(
                        default=True, help_text="Use TLS (usually for port 587)"
                    ),
                ),
                (
                    "email_use_ssl",
                    models.BooleanField(
                        default=False, help_text="Use SSL (usually for port 465)"
                    ),
                ),
                (
                    "default_from_email",
                    models.EmailField(
                        blank=True, help_text="Default Sender Email", max_length=254
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
    ]
