# Generated by Django 5.0.7 on 2025-12-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="address",
            field=models.TextField(default="123 Luxury Ave, Paradise City"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="contact_email",
            field=models.EmailField(default="info@grandhotel.com", max_length=254),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="contact_phone",
            field=models.CharField(default="+1 234 567 8900", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="facebook_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="hotel_logo",
            field=models.ImageField(blank=True, null=True, upload_to="site/"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="hotel_name",
            field=models.CharField(default="Grand Hotel", max_length=255),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="instagram_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="twitter_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="theme",
            field=models.CharField(
                choices=[
                    ("theme-default", "Default Dark"),
                    ("theme-light", "Light Mode"),
                    ("theme-blue", "Blue Horizon"),
                    ("theme-luxury", "Gold Luxury"),
                    ("theme-forest", "Forest Green"),
                    ("theme-ocean", "Ocean Breeze"),
                    ("theme-sunset", "Sunset Vibes"),
                    ("theme-royal", "Royal Purple"),
                    ("theme-minimal", "Minimalist Mono"),
                ],
                default="theme-default",
                max_length=50,
            ),
        ),
    ]
