# Generated by Django 5.0.7 on 2026-01-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_host",
                    models.CharField(default="mail.techohr.com.ng", max_length=255),
                ),
                ("email_port", models.IntegerField(default=465)),
                (
                    "email_host_user",
                    models.CharField(default="ihotel@techohr.com.ng", max_length=255),
                ),
                ("email_host_password", models.CharField(blank=True, max_length=255)),
                ("email_use_tls", models.BooleanField(default=False)),
                ("email_use_ssl", models.BooleanField(default=True)),
                (
                    "default_from_email",
                    models.EmailField(default="ihotel@techohr.com.ng", max_length=254),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tenantsetting",
            name="default_from_email",
            field=models.EmailField(
                blank=True, help_text="Default Sender Email", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="tenantsetting",
            name="email_host",
            field=models.CharField(
                blank=True,
                help_text="SMTP Server (e.g., smtp.gmail.com)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="tenantsetting",
            name="email_host_password",
            field=models.CharField(
                blank=True, help_text="Email Password", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="tenantsetting",
            name="email_host_user",
            field=models.CharField(
                blank=True, help_text="Email Address", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="tenantsetting",
            name="email_port",
            field=models.IntegerField(
                default=587, help_text="SMTP Port (e.g., 587 or 465)"
            ),
        ),
        migrations.AddField(
            model_name="tenantsetting",
            name="email_use_ssl",
            field=models.BooleanField(
                default=False, help_text="Use SSL (usually for port 465)"
            ),
        ),
        migrations.AddField(
            model_name="tenantsetting",
            name="email_use_tls",
            field=models.BooleanField(
                default=True, help_text="Use TLS (usually for port 587)"
            ),
        ),
    ]
