# Generated by Django 5.0.7 on 2026-01-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantsetting",
            name="address",
            field=models.TextField(blank=True, default="123 Luxury Ave, City"),
        ),
        migrations.AlterField(
            model_name="tenantsetting",
            name="contact_email",
            field=models.EmailField(
                blank=True, default="info@example.com", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="tenantsetting",
            name="contact_phone",
            field=models.CharField(
                blank=True, default="+1 234 567 8900", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="tenantsetting",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USD", "USD ($)"),
                    ("EUR", "EUR (€)"),
                    ("GBP", "GBP (£)"),
                    ("NGN", "NGN (₦)"),
                    ("JPY", "JPY (¥)"),
                    ("CAD", "CAD ($)"),
                    ("AUD", "AUD ($)"),
                    ("INR", "INR (₹)"),
                    ("ZAR", "ZAR (R)"),
                ],
                default="NGN",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="tenantsetting",
            name="custom_background_color",
            field=models.CharField(
                blank=True,
                default="#0f172a",
                help_text="Hex code for background color",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="tenantsetting",
            name="custom_primary_color",
            field=models.CharField(
                blank=True,
                default="#13ec6d",
                help_text="Hex code for primary color",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="tenantsetting",
            name="custom_surface_color",
            field=models.CharField(
                blank=True,
                default="#1e293b",
                help_text="Hex code for surface/card color",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="tenantsetting",
            name="email_port",
            field=models.IntegerField(
                blank=True,
                default=587,
                help_text="SMTP Port (e.g., 587 or 465)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tenantsetting",
            name="hotel_name",
            field=models.CharField(blank=True, default="My Hotel", max_length=255),
        ),
    ]
