# Generated by Django 5.0.7 on 2026-01-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_tenantsetting_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsetting",
            name="hotel_description",
            field=models.TextField(
                blank=True,
                default="Experience a world of comfort and elegance in the heart of the city. Your perfect gateway begins here.",
                help_text="Short description for the footer",
            ),
        ),
        migrations.AddField(
            model_name="tenantsetting",
            name="hotel_tagline",
            field=models.CharField(
                blank=True,
                default="Luxury Stay",
                help_text="A short tagline shown below the hotel name",
                max_length=255,
            ),
        ),
    ]
