# Generated by Django 5.0.7 on 2026-01-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "USD ($)"),
                    ("EUR", "EUR (€)"),
                    ("GBP", "GBP (£)"),
                    ("NGN", "NGN (₦)"),
                    ("JPY", "JPY (¥)"),
                    ("CAD", "CAD ($)"),
                    ("AUD", "AUD ($)"),
                    ("INR", "INR (₹)"),
                    ("ZAR", "ZAR (R)"),
                ],
                default="USD",
                max_length=10,
            ),
        ),
    ]
