# Generated by Django 5.0.7 on 2026-01-14 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_tenantsetting_hotel_description_and_more"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsetting",
            name="hero_background",
            field=models.ImageField(
                blank=True,
                help_text="Main hero background image",
                null=True,
                upload_to="site/hero/",
            ),
        ),
        migrations.AddField(
            model_name="tenantsetting",
            name="hero_cta_link",
            field=models.CharField(blank=True, default="#rooms", max_length=255),
        ),
        migrations.AddField(
            model_name="tenantsetting",
            name="hero_cta_text",
            field=models.CharField(blank=True, default="Book Now", max_length=50),
        ),
        migrations.AddField(
            model_name="tenantsetting",
            name="hero_subtitle",
            field=models.CharField(
                blank=True,
                default="Discover comfort, elegance, and unforgettable moments.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="tenantsetting",
            name="hero_title",
            field=models.CharField(
                blank=True, default="Experience Luxury", max_length=255
            ),
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "subject",
                    models.CharField(default="General Inquiry", max_length=255),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_messages",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
    ]
