# Generated by Django 5.0.7 on 2026-01-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_sitesetting_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="custom_background_color",
            field=models.CharField(
                default="#0f172a",
                help_text="Hex code for background color",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="custom_primary_color",
            field=models.CharField(
                default="#13ec6d", help_text="Hex code for primary color", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="custom_surface_color",
            field=models.CharField(
                default="#1e293b",
                help_text="Hex code for surface/card color",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="theme",
            field=models.CharField(
                choices=[
                    ("theme-default", "Default Dark"),
                    ("theme-light", "Light Mode"),
                    ("theme-blue", "Blue Horizon"),
                    ("theme-luxury", "Gold Luxury"),
                    ("theme-forest", "Forest Green"),
                    ("theme-ocean", "Ocean Breeze"),
                    ("theme-sunset", "Sunset Vibes"),
                    ("theme-royal", "Royal Purple"),
                    ("theme-minimal", "Minimalist Mono"),
                    ("theme-rose", "Rose Garden"),
                    ("theme-coffee", "Coffee Break"),
                    ("theme-lavender", "Lavender Mist"),
                    ("theme-midnight", "Midnight Run"),
                    ("theme-custom", "Custom Theme"),
                ],
                default="theme-default",
                max_length=50,
            ),
        ),
    ]
