# Generated by Django 5.0.7 on 2026-01-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_tenantsetting_hero_background_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsetting",
            name="faq_content",
            field=models.TextField(
                blank=True,
                default="No FAQs available yet.",
                help_text="HTML content for FAQs page",
            ),
        ),
        migrations.AddField(
            model_name="tenantsetting",
            name="privacy_policy",
            field=models.TextField(
                blank=True,
                default="Privacy Policy content goes here.",
                help_text="HTML content for Privacy Policy page",
            ),
        ),
        migrations.AddField(
            model_name="tenantsetting",
            name="terms_conditions",
            field=models.TextField(
                blank=True,
                default="Terms and Conditions content goes here.",
                help_text="HTML content for Terms & Conditions page",
            ),
        ),
    ]
