# Generated by Django 5.0.7 on 2026-01-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_sitesetting_custom_background_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="housekeeping_info",
            field=models.TextField(
                blank=True,
                default="Standard housekeeping is available from 9:00 AM to 5:00 PM daily. Please request special services at least 2 hours in advance.",
                help_text="Information about cleaning schedules and policies.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="theme",
            field=models.CharField(
                choices=[
                    ("theme-default", "Default Dark"),
                    ("theme-light", "Light Mode"),
                    ("theme-blue", "Blue Horizon"),
                    ("theme-luxury", "Gold Luxury"),
                    ("theme-forest", "Forest Green"),
                    ("theme-ocean", "Ocean Breeze"),
                    ("theme-sunset", "Sunset Vibes"),
                    ("theme-royal", "Royal Purple"),
                    ("theme-minimal", "Minimalist Mono"),
                    ("theme-rose", "Rose Garden"),
                    ("theme-coffee", "Coffee Break"),
                    ("theme-lavender", "Lavender Mist"),
                    ("theme-midnight", "Midnight Run"),
                    ("theme-neon", "Neon Cyberpunk"),
                    ("theme-retro", "Retro Wave"),
                    ("theme-cherry", "Cherry Blossom"),
                    ("theme-dracula", "Dracula Dark"),
                    ("theme-corporate", "Corporate Professional"),
                    ("theme-custom", "Custom Theme"),
                ],
                default="theme-default",
                max_length=50,
            ),
        ),
    ]
