# Generated by Django 5.0.7 on 2026-01-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_sitesetting_housekeeping_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="enable_events",
            field=models.BooleanField(
                default=False,
                help_text="Enable Events Management module (Halls, Bookings)",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="enable_gym",
            field=models.BooleanField(
                default=False,
                help_text="Enable Gym & Fitness module (Memberships, Access)",
            ),
        ),
    ]
