# Generated by Django 5.0.7 on 2026-01-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_tenantsetting_faq_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsetting",
            name="booking_id_prefix",
            field=models.CharField(
                blank=True,
                default="HMS",
                help_text="Prefix for booking IDs (e.g., HMS -> HMS-2024-0001)",
                max_length=10,
            ),
        ),
    ]
