# Generated by Django 5.0.7 on 2026-01-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_tenantsetting_booking_id_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsetting",
            name="about_us_content",
            field=models.TextField(
                blank=True,
                default='<h2 class="text-3xl font-bold text-text-main">Our Story</h2>\n<p class="text-text-secondary-dark leading-relaxed">\n    Founded with a vision to redefine hospitality, our hotel stands as a beacon of elegance and service. \n    Every corner of our hotel is designed with your comfort in mind, blending contemporary aesthetics with timeless charm.\n</p>\n<p class="text-text-secondary-dark leading-relaxed">\n    Whether you are here for business or leisure, our dedicated team is committed to ensuring your stay is nothing short of perfection.\n</p>',
                help_text="HTML content for About Us page (Our Story section)",
            ),
        ),
        migrations.AddField(
            model_name="tenantsetting",
            name="why_choose_us_content",
            field=models.TextField(
                blank=True,
                default='<div class="grid grid-cols-1 md:grid-cols-3 gap-8">\n    <div class="text-center space-y-4">\n        <div class="size-16 rounded-full bg-primary/10 flex items-center justify-center mx-auto text-primary">\n            <span class="material-symbols-outlined text-3xl">diamond</span>\n        </div>\n        <h3 class="text-xl font-bold text-text-main">Premium Comfort</h3>\n        <p class="text-text-secondary-dark text-sm">Experience the pinnacle of luxury with our carefully curated amenities and spaces.</p>\n    </div>\n    <div class="text-center space-y-4">\n        <div class="size-16 rounded-full bg-primary/10 flex items-center justify-center mx-auto text-primary">\n            <span class="material-symbols-outlined text-3xl">restaurant</span>\n        </div>\n        <h3 class="text-xl font-bold text-text-main">Exquisite Dining</h3>\n        <p class="text-text-secondary-dark text-sm">Savor culinary masterpieces prepared by our world-class chefs.</p>\n    </div>\n    <div class="text-center space-y-4">\n        <div class="size-16 rounded-full bg-primary/10 flex items-center justify-center mx-auto text-primary">\n            <span class="material-symbols-outlined text-3xl">spa</span>\n        </div>\n        <h3 class="text-xl font-bold text-text-main">Relaxation</h3>\n        <p class="text-text-secondary-dark text-sm">Unwind and rejuvenate in our state-of-the-art wellness centers.</p>\n    </div>\n</div>',
                help_text="HTML content for Why Choose Us section",
            ),
        ),
    ]
