# Generated by Django 5.0.7 on 2026-01-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_tenantsetting_about_us_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsetting",
            name="custom_accent_color",
            field=models.CharField(
                blank=True,
                default="#f59e0b",
                help_text="Hex code for accent color (Gold/Yellow)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="tenantsetting",
            name="custom_button_color",
            field=models.CharField(
                blank=True,
                default="#f59e0b",
                help_text="Hex code for button background color",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="tenantsetting",
            name="custom_button_text_color",
            field=models.CharField(
                blank=True,
                default="#ffffff",
                help_text="Hex code for button text color",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="tenantsetting",
            name="custom_secondary_color",
            field=models.CharField(
                blank=True,
                default="#1e293b",
                help_text="Hex code for secondary color",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="tenantsetting",
            name="custom_text_color",
            field=models.CharField(
                blank=True,
                default="#ffffff",
                help_text="Hex code for main text color",
                max_length=7,
            ),
        ),
    ]
