# Generated by Django 5.0.7 on 2026-01-23 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_tenantsetting_custom_accent_color_and_more"),
        ("tenants", "0003_tenant_location_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelFacility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Short description of the facility"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Material Symbol name (e.g. wifi, pool, spa)",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilities",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Hotel Facilities",
                "ordering": ["order", "name"],
            },
        ),
    ]
