# Generated by Django 5.0.7 on 2026-01-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_hotelfacility"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsetting",
            name="custom_card_background_color",
            field=models.CharField(
                blank=True,
                default="#0f172a",
                help_text="Hex code for listing cards (Rooms, Halls, Plans)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="tenantsetting",
            name="custom_section_background_color",
            field=models.CharField(
                blank=True,
                default="#0f172a",
                help_text="Hex code for page sections",
                max_length=7,
            ),
        ),
    ]
