# Generated by Django 5.0.7 on 2026-01-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="payment_auth_code",
            field=models.CharField(
                blank=True,
                help_text="Token for recurring payments",
                max_length=255,
                null=True,
            ),
        ),
    ]
