# Generated by Django 5.0.7 on 2026-01-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="font_family",
            field=models.CharField(default="Inter", max_length=50),
        ),
        migrations.AddField(
            model_name="tenant",
            name="secondary_color",
            field=models.CharField(default="#1e293b", max_length=7),
        ),
    ]
