# Generated by Django 5.0.7 on 2026-01-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenant_font_family_tenant_secondary_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="auto_renew",
            field=models.BooleanField(default=True),
        ),
    ]
