# Generated by Django 5.0.7 on 2026-01-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenant_location_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="tenant",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
