# Generated by Django 5.0.7 on 2026-01-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_tenant_billing_cycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="allow_custom_domain",
            field=models.BooleanField(
                default=False, help_text="Allow custom domains and subdomains"
            ),
        ),
    ]
