# Generated by Django 5.0.7 on 2026-01-12 08:49

from django.db import migrations

def update_premium_plans(apps, schema_editor):
    Plan = apps.get_model('tenants', 'Plan')
    # Update plans with 'premium' or 'pro' in their name to allow custom domains
    Plan.objects.filter(name__icontains='premium').update(allow_custom_domain=True)
    Plan.objects.filter(name__icontains='pro').update(allow_custom_domain=True)

class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_plan_allow_custom_domain"),
    ]

    operations = [
        migrations.RunPython(update_premium_plans),
    ]
