# Generated by Django 5.0.7 on 2026-01-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_update_premium_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="module_events",
            field=models.BooleanField(
                default=False, help_text="Enable Event Halls & Booking System"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="module_gym",
            field=models.BooleanField(
                default=False, help_text="Enable Gym Membership Management"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="module_housekeeping",
            field=models.BooleanField(
                default=True, help_text="Enable Housekeeping Requests"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="module_restaurant",
            field=models.BooleanField(
                default=False, help_text="Enable Restaurant Menu & Orders"
            ),
        ),
    ]
