# Generated by Django 5.0.7 on 2026-01-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0007_plan_module_events_plan_module_gym_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="currency",
            field=models.CharField(
                choices=[
                    ("NGN", "Nigerian Naira"),
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                ],
                default="NGN",
                max_length=3,
            ),
        ),
    ]
