# Generated by Django 5.0.7 on 2026-01-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0008_plan_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="allow_custom_email",
            field=models.BooleanField(
                default=False, help_text="Allow custom SMTP email configuration"
            ),
        ),
    ]
