# Generated by Django 5.0.7 on 2026-01-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("AWAITING_PAYMENT", "Awaiting Payment"),
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
