# Generated by Django 5.0.7 on 2026-01-18 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_guestorder_status'),
        ('tenants', '0002_tenant_payment_auth_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestorder',
            name='order_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='housekeepingrequest',
            name='request_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='housekeepingservicetype',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_service_types', to='tenants.tenant'),
        ),
    ]
