# Generated by Django 5.0.7 on 2026-01-06 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_housekeepingrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="HousekeepingServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        default="cleaning_services",
                        help_text="Material Symbol icon name",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="housekeepingrequest",
            name="request_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CLEANING", "Room Cleaning"),
                    ("TOWELS", "Extra Towels"),
                    ("TOILETRIES", "Toiletries"),
                    ("MAINTENANCE", "Maintenance Issue"),
                    ("OTHER", "Other"),
                ],
                default="CLEANING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="housekeepingrequest",
            name="service_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests",
                to="services.housekeepingservicetype",
            ),
        ),
    ]
