# Generated by Django 5.0.7 on 2026-01-06 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_paymentgateway_alter_payment_payment_method"),
        ("services", "0004_housekeepingservicetype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestorder",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="billing.invoice",
            ),
        ),
    ]
