# Generated by Django 5.0.7 on 2026-01-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("MANAGER", "Manager"),
                    ("RECEPTIONIST", "Receptionist"),
                    ("STAFF", "Staff"),
                    ("CLEANER", "Cleaner"),
                    ("KITCHEN", "Kitchen Staff"),
                    ("GUEST", "Guest"),
                ],
                default="GUEST",
                max_length=50,
            ),
        ),
    ]
