# Generated by Django 5.0.7 on 2026-01-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="check_in_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_out_date",
            field=models.DateTimeField(),
        ),
    ]
