# Generated by Django 5.0.7 on 2026-01-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_reference",
            field=models.CharField(
                blank=True,
                help_text="Unique booking ID per tenant",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="sequence_number",
            field=models.PositiveIntegerField(
                default=0, help_text="Sequential number for this tenant's bookings"
            ),
        ),
    ]
