# Generated by Django 5.0.7 on 2025-12-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomtype",
            name="amenities",
            field=models.TextField(
                blank=True, help_text="Comma-separated list of amenities"
            ),
        ),
    ]
