# Generated by Django 5.0.7 on 2026-01-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomtype",
            name="amenities",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of amenities (e.g. WiFi, Pool, Breakfast)",
            ),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="description",
            field=models.TextField(
                blank=True, help_text="Detailed description of the room type"
            ),
        ),
    ]
