# Generated by Django 5.0.7 on 2025-12-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0003_roomimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomtype",
            name="number_of_rooms",
            field=models.PositiveIntegerField(
                default=1, help_text="Total number of rooms for this category"
            ),
        ),
    ]
